### ISSUE TITLE
Problem in Loading model checkpoint 

### ISSUE THREAD

**Issue by ankugupt** [wenhuchen/Table-Fact-Checking#10]
I am trying to run LPA on my custom dataset. My aim is to load the checkpoint and fine-tuning on my dataset but I am getting this error while loading the checkpoint: 

File "model.py", line 205, in <module>
    encoder_prog.load_state_dict(torch.load(args.output_dir + "encoder_prog_{}.pt".format(args.id)))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Decoder:
	size mismatch for tgt_word_emb.weight: copying a param with shape torch.Size([148791, 128]) from checkpoint, the shape in current model is torch.Size([68717, 128]). 

On analyzing the code the problem looks due to different vocab size. Is there any way to fine-tune my dataset on the provided checkpoint? 

Thanks!

**Comment by wenhuchen** [comment]
I don't know what is your customed dataset, could you just select the overlapped vocabulary of my checkpoint and your dataset and set the rest to random initialization?

**Comment by jaihonikhil** [comment]
Hello, Can you please share the vocab.json file which you would have created using the Tabfact dataset for the method mentioned as you? I am also facing the same issue as mentioned by @ankugupt .
Thanks

**Comment by wenhuchen** [comment]
I just added the vocab.json in the following path:
https://github.com/wenhuchen/Table-Fact-Checking/blob/master/preprocessed_data_program/vocab.json

**Comment by wenhuchen** [comment]
> I am trying to run LPA on my custom dataset. My aim is to load the checkpoint and fine-tuning on my dataset but I am getting this error while loading the checkpoint:
> 
> File "model.py", line 205, in
> encoder_prog.load_state_dict(torch.load(args.output_dir + "encoder_prog_{}.pt".format(args.id)))
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
> self.**class**.**name**, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for Decoder:
> size mismatch for tgt_word_emb.weight: copying a param with shape torch.Size([148791, 128]) from checkpoint, the shape in current model is torch.Size([68717, 128]).
> 
> On analyzing the code the problem looks due to different vocab size. Is there any way to fine-tune my dataset on the provided checkpoint?
> 
> Thanks!

The vocab.json is in https://github.com/wenhuchen/Table-Fact-Checking/blob/master/preprocessed_data_program/vocab.json
