### ISSUE TITLE
Question: Are the sentences prior to rewriting available?

### ISSUE THREAD

**Issue by eisenjulian** [wenhuchen/Table-Fact-Checking#4]
Hi Wenhu, thanks for making all of these open-source! I was wondering if the positive sentences that were rewritten into negative ones are available in the repo as well, or if you would consider doing so, since I think it would be an interesting (albeit different) task as well.

**Comment by wenhuchen** [comment]
Yes, I do. I can re-download the data from Mechanical Turk interface, I will share with you once I have it ready.

**Comment by wenhuchen** [comment]
Hi, I just crawled the data from the AMT interface and upload it to the repo with the link "https://github.com/wenhuchen/Table-Fact-Checking/tree/master/pairwise_data". Please note that the data is pretty raw without much preprocessing, but I'm sure you can handle them well.

**Comment by eisenjulian** [comment]
Awesome, thank you so much!
