### ISSUE TITLE
Can not reproduce the results obtained when training

### ISSUE THREAD

**Issue by qshi95** [wenhuchen/Table-Fact-Checking#5]
Hi wenhu, when evaluating the checkpoints trained with the provided code, I can't get the same results with the results when training. Is my model not loaded correctly? Do you know how to deal with the problem? Thank you very much!

**Comment by wenhuchen** [comment]
Which model do you refer to, could you also provide your command to run the code?

**Comment by qshi95** [comment]
Table-BERT
The command is python run_BERT.py --do_train --do_eval --scan horizontal --fact first

I didn't get the same result evaluating during training and after training.

**Comment by wenhuchen** [comment]
Could you please tell me what is the score you get? the code should be able to achieve a higher score than reported in the paper from my experience.

**Comment by qshi95** [comment]
Yeah, I got 67.5 on dev set. There is no problem during training. The problem appears in the time when evaluating the checkpoints.

**Comment by wenhuchen** [comment]
Hi, I just ran the code and found out the results are slightly different (0.6754255739843237 vs. 0.6509264326479556). Is there a huge difference on your side?

**Comment by qshi95** [comment]
There is also a gap of about two points on my side. The two results are the same checkpoint on the dev set. I think the gap is not small.

**Comment by wenhuchen** [comment]
Jus fixed the problem, it's because I didn't set the model into eval mode before evaluation. I added this line to fix it.

https://github.com/wenhuchen/Table-Fact-Checking/blob/3020f6082aa9bf49b3261fc8d863228f696d795b/code/run_BERT.py#L689

**Comment by qshi95** [comment]
Thanks. It works.

**Comment by qshi95** [comment]
Hi wenhu, is the "concatenation" method of Table-BERT available in the repo? Thanks a lot!
