### ISSUE TITLE
"Concatenation" method

### ISSUE THREAD

**Issue by qshi95** [wenhuchen/Table-Fact-Checking#6]
Hi wenhu, is the "concatenation" method of Table-BERT available in the repo? Thanks a lot!

**Comment by wenhuchen** [comment]
The Table BERT is the concatenation one，which one do you refer to？

**Comment by qshi95** [comment]
In the paper, there are two methods, "concatenation" and "template". I only found "template" method in your code. Is "concatenation" also available?

**Comment by wenhuchen** [comment]
Ah, got you. I don't have the code right now, but its performance is really bad, you can simply modify the current template to reproduce it.

**Comment by qshi95** [comment]
OK I know. Thank you~
